### ISSUE TITLE
Support importing NgxMatomoTrackerModule in lazy-loaded modules

### ISSUE THREAD

**Issue by EmmanuelRoux** [EmmanuelRoux/ngx-matomo-client#7]
Add support for importing NgxMatomoTrackerModule (and NgxMatomoRouterModule) in lazy-loaded modules

**Comment by EmmanuelRoux** [comment]
@dtomaszewski maybe this would suits your needs?
It should be coming very soon (in just a few days)

**Comment by dtomaszewski** [comment]
@EmmanuelRoux I'll definitely try it :)
